# Data Loading

In [ ]:
TOTAL_LABEL=["Image_path"]+column_labels_name
TOTAL_LABEL

['Image_path', '0-2', '4-6', '8-13', '15-20', '25-32', '38-43', '48-53', '60+']

In [ ]:
train_age_df = train[TOTAL_LABEL]
train_gender_df = train[["Image_path", "Gender_label"]]

test_age_df = test[TOTAL_LABEL]
test_gender_df = test[["Image_path", "Gender_label"]]

train_age_df.head()

,Image_path,0-2,4-6,8-13,15-20,25-32,38-43,48-53,60+
0,/content/adience-benchmark-gender-and-age-clas...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,/content/adience-benchmark-gender-and-age-clas...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,/content/adience-benchmark-gender-and-age-clas...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/content/adience-benchmark-gender-and-age-clas...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,/content/adience-benchmark-gender-and-age-clas...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [ ]:
# converting back to string because CNNs need a categorical input
train_age_df[column_labels_name] = train_age_df[column_labels_name].astype(int)
test_age_df[column_labels_name] = test_age_df[column_labels_name].astype(int)

train_gen = tf.keras.preprocessing.image.ImageDataGenerator(preprocessing_function = tf.keras.applications.efficientnet_v2.preprocess_input,
                                                            validation_split=0.2)
test_gen = tf.keras.preprocessing.image.ImageDataGenerator(preprocessing_function = tf.keras.applications.efficientnet_v2.preprocess_input)
BATCH_SIZE=64
IMG_SIZE = 224
RANDOM_SEED = 42

train_generator = train_gen.flow_from_dataframe(
    dataframe=train_age_df,
    directory="",
    x_col="Image_path",
    y_col=column_labels_name,
    subset="training",
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE, # 32 default
    class_mode='raw',
    shuffle=True, 
    seed=RANDOM_SEED,
    )

val_generator = train_gen.flow_from_dataframe(
    dataframe=train_age_df,
    directory="",
    x_col="Image_path",
    y_col=column_labels_name,
    subset="validation",
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE, # 32 default
    class_mode='raw',
    shuffle=True, 
    seed=RANDOM_SEED,
    )

test_generator = test_gen.flow_from_dataframe(
    dataframe=test_age_df,
    directory="",
    x_col="Image_path",
    y_col=column_labels_name,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='raw',
    shuffle=True, 
    seed=RANDOM_SEED,
    )

<ipython-input-47-0f411b6a8278>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_age_df[column_labels_name] = train_age_df[column_labels_name].astype(int)
<ipython-input-47-0f411b6a8278>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_age_df[column_labels_name] = test_age_df[column_labels_name].astype(int)

Found 9773 validated image filenames.
Found 2443 validated image filenames.
Found 5236 validated image filenames.